BITS	16
ORG		0x7c00

JMP		entry
DB		0x90
DB		"HELLOIPL"
DW		512
DB		1
DW		1
DB		2
DW		224
DW		2880
DB		0xf0
DW		9
DW		18
DW		2
DD		0
DD		2880
DB		0, 0, 0x29
DD		0xffffffff
DB		"HELLO-OS   "
DB		"FAT12   "
RESB	18

entry:
MOV		ax, 0
MOV		ss, ax
MOV		sp, 0x7c00
MOV		ds, ax
MOV		es, ax

MOV		si, msg

putloop:
MOV		al, [si]
ADD		si, 1
CMP		al, 0
JE		fin
MOV		ah, 0x0e
MOV		bx, 15
INT		0x10
JMP		putloop

fin:
HLT
JMP		fin

msg:
DB		0x0a, 0x0a
DB		"hello world"
DB		0x0a
DB		0

TIMES	510-($-$$)	DB	0

DB		0x55, 0xaa
